### ISSUE TITLE
Change not published: Remove master branch?

### ISSUE THREAD

**Issue by gagarine** [constantin-p/macports-site#3]
My pull request get merged in master. But I realise now that is the gh-page is the branch that get published.

I think we can keep only one branch and publish it no for the moment? Either by changing with branch get published (in the settings of github page) or by removing master after merging it in gh-page.

**Comment by gagarine** [comment]
The pull request in question: https://github.com/constantin-p/macports-site/pull/2

**Comment by constantin-p** [comment]
Changes from [PR#2](https://github.com/constantin-p/macports-site/pull/2) published with be7963f781105550be2ff31539fc2d56a85a48ba .

`master` contains the templates, config & content files that are used to generate the static website. They do not need to be published so `gh-pages` is set up to mirror just the public folder (the output of the build process).
